#!/usr/bin/env python3
"""Generate config/recording.toml with the NIFTY-50 equity universe (+ index).

Reads OpenAPIScripMaster.json (Angel One instrument master) and resolves each
NIFTY-50 stock name to its NSE cash-equity token (the "-EQ" series), then writes
config/recording.toml — the universe the Phase 0 ingestion recorder subscribes
to.

Run from the repo root:
    python scripts/extract_nifty50_tokens.py

Re-run before a fresh data-collection campaign or whenever the index is
rebalanced. The traded universe (config/trading.toml) is deliberately separate:
we RECORD wide and TRADE narrow.
"""
import json
import os
import sys

# NIFTY-50 constituents. The index is rebalanced periodically — verify this list
# against the current NSE composition before a long recording campaign.
NIFTY50 = [
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
    "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL", "BPCL",
    "BRITANNIA", "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "GRASIM",
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR",
    "ICICIBANK", "INDUSINDBK", "INFY", "ITC", "JSWSTEEL", "KOTAKBANK", "LT",
    "LTIM", "M&M", "MARUTI", "NESTLEIND", "NTPC", "ONGC", "POWERGRID",
    "RELIANCE", "SBILIFE", "SBIN", "SHRIRAMFIN", "SUNPHARMA", "TATACONSUM",
    "TATAMOTORS", "TATASTEEL", "TCS", "TECHM", "TITAN", "TRENT", "ULTRACEMCO",
    "WIPRO",
]

# NIFTY 50 spot index (Angel One token).
NIFTY_INDEX_TOKEN = "26000"

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPMASTER = os.path.join(REPO_ROOT, "OpenAPIScripMaster.json")
OUT = os.path.join(REPO_ROOT, "config", "recording.toml")


def main():
    with open(SCRIPMASTER, "r") as f:
        data = json.load(f)

    # Index NSE cash-equity ("-EQ") rows by name for quick lookup.
    eq_by_name = {}
    for item in data:
        if item.get("exch_seg") == "NSE" and str(item.get("symbol", "")).endswith("-EQ"):
            eq_by_name[item["name"]] = item

    resolved, missing = [], []
    for name in NIFTY50:
        rec = eq_by_name.get(name)
        if rec:
            resolved.append((name, rec["token"], rec["symbol"]))
        else:
            missing.append(name)

    out = []
    out.append("# Market-data RECORDING universe (auto-generated by")
    out.append("# scripts/extract_nifty50_tokens.py). Record wide, trade narrow:")
    out.append("# the TRADED universe lives in config/trading.toml.")
    out.append("#")
    out.append(f"# Resolved {len(resolved)}/{len(NIFTY50)} NIFTY-50 names from ScripMaster.")
    if missing:
        out.append(f"# NOT FOUND (check names / index composition): {', '.join(missing)}")
    out.append("")
    out.append("# NIFTY 50 spot index.")
    out.append("[[instruments]]")
    out.append('symbol         = "NIFTY"')
    out.append(f"token          = {NIFTY_INDEX_TOKEN}")
    out.append('trading_symbol = "NIFTY50"')
    out.append('exchange       = "NSE"')
    out.append("")
    out.append("# To also record the active NIFTY future, add an [[instruments]]")
    out.append('# entry with exchange = "NFO" (its token changes monthly).')
    out.append("")
    for name, token, symbol in resolved:
        out.append("[[instruments]]")
        out.append(f'symbol         = "{name}"')
        out.append(f"token          = {token}")
        out.append(f'trading_symbol = "{symbol}"')
        out.append('exchange       = "NSE"')
        out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")

    print(f"Wrote {OUT}: {len(resolved)} equities + 1 index.")
    if missing:
        print(f"WARNING: {len(missing)} name(s) not found: {', '.join(missing)}", file=sys.stderr)


if __name__ == "__main__":
    main()
